# Generated by Django 3.1.3 on 2020-12-04 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201128_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
