# Generated by Django 3.1.3 on 2020-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201207_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_post_images/'),
        ),
    ]
