# Generated by Django 3.1.3 on 2020-12-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201210_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
    ]
